name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cherryred5959/soundcloud-clone-backend:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle wrapper
        run: gradle wrapper

      - name: Testing with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build
