name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cherryred5959/soundcloud-clone-backend:latest
    services:
      mariadb:
        image: mariadb:10.5.8-focal
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MARIADB_DATABASE }}
          MYSQL_USER: ${{ secrets.MARIADB_USER }}
          MYSQL_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Clone environment repository code
        uses: actions/checkout@v2
        with:
          repository: mtudy/soundcloud-clone-environment
          token: ${{ secrets.BUILD_KEY }}
          path: .environment

      - name: Inject environment file
        run: cp -a .environment/backend/application-default.properties src/test/resources/

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle wrapper
        run: gradle wrapper

      - name: Testing with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build
